openapi: 3.0.0
info:
  title: Vue Express API
  version: 1.0.0
  description: API for Vue Express fullstack sample application
servers:
  - url: http://localhost:3001
    description: Development server
paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /microposts:
    get:
      summary: Get all microposts
      operationId: getMicroposts
      responses:
        '200':
          description: List of microposts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Micropost'
    post:
      summary: Create a new micropost
      operationId: createMicropost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMicropostRequest'
      responses:
        '201':
          description: Created micropost
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Micropost'
  /microposts/{id}:
    get:
      summary: Get a micropost by ID
      operationId: getMicropostById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Micropost details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Micropost'
        '404':
          description: Micropost not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Micropost:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        userId:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateMicropostRequest:
      type: object
      required:
        - title
        - userId
      properties:
        title:
          type: string
        userId:
          type: integer
