openapi: 3.0.3
info:
  title: Cloud-Shop Loans Service API
  description: CRUD REST APIs in Cloud-Shop to CREATE, UPDATE, FETCH AND DELETE loan details
  version: 1.0.0
  contact:
    name: Kuro Bytes
    email: support@kurobytes.com

paths:
  /api/create:
    post:
      operationId: createLoan
      summary: Create Loan REST API
      description: REST API to create new Loan inside Cloud-Shop
      parameters:
        - name: mobileNumber
          in: query
          required: true
          schema:
            type: string
            pattern: '^[0-9]{10}$'
          description: Mobile number must be 10 digits
      responses:
        '201':
          description: HTTP Status CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDto'
        '500':
          description: HTTP Status Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /api/fetch:
    get:
      operationId: fetchLoan
      summary: Fetch Loan Details REST API
      description: REST API to fetch loan details based on a mobile number
      parameters:
        - name: cloud-shop-correlation-id
          in: header
          required: false
          schema:
            type: string
        - name: mobileNumber
          in: query
          required: true
          schema:
            type: string
            pattern: '^[0-9]{10}$'
          description: Mobile number must be 10 digits
      responses:
        '200':
          description: HTTP Status OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoansDto'
        '500':
          description: HTTP Status Internal Server Error

  /api/update:
    put:
      operationId: updateLoan
      summary: Update Loan Details REST API
      description: REST API to update loan details based on a loan number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoansDto'
      responses:
        '200':
          description: HTTP Status OK
        '417':
          description: Expectation Failed
        '500':
          description: HTTP Status Internal Server Error

  /api/delete:
    delete:
      operationId: deleteLoan
      summary: Delete Loan Details REST API
      description: REST API to delete Loan details based on a mobile number
      parameters:
        - name: mobileNumber
          in: query
          required: true
          schema:
            type: string
            pattern: '^[0-9]{10}$'
      responses:
        '200':
          description: HTTP Status OK
        '417':
          description: Expectation Failed
        '500':
          description: HTTP Status Internal Server Error

  /api/build-info:
    get:
      operationId: getBuildInfo
      summary: Get Build information
      responses:
        '200':
          description: HTTP Status OK

  /api/contact-info:
    get:
      operationId: getContactInfo
      summary: Get Contact Info
      responses:
        '200':
          description: HTTP Status OK

  /actuator/health:
    get:
      operationId: healthCheck
      summary: Health Check
      responses:
        '200':
          description: Service is healthy

components:
  schemas:
    LoansDto:
      type: object
      properties:
        mobileNumber:
          type: string
          pattern: '^[0-9]{10}$'
        loanNumber:
          type: string
        loanType:
          type: string
        totalLoan:
          type: integer
        amountPaid:
          type: integer
        outstandingAmount:
          type: integer
      required:
        - mobileNumber
        - loanNumber
        - loanType
        - totalLoan
        - amountPaid
        - outstandingAmount

    ResponseDto:
      type: object
      properties:
        statusCode:
          type: string
        statusMsg:
          type: string

    ErrorResponseDto:
      type: object
      properties:
        apiPath:
          type: string
        errorCode:
          type: string
        errorMessage:
          type: string
        errorTime:
          type: string
